### PR TITLE
pulling highest value from supported_versions extension

### PR DESCRIPTION
**Pull request by superstes**
See: #11

### CODE REVIEW

**Comment by superstes** [comment]
@mat1010 Do you mind looking over it?
I guess we could do a binary comparison, which might be cheaper than  `Binary => Int/String => Array Split =[LOOP]=> Int`

**Comment by superstes** [comment]
BTW: `ssl_fc_supported_versions_bin(1)` with the `(1)` did die on me as the GREASE is not yet in the branch (?)

**Comment by mat1010** [comment]
> @mat1010 Do you mind looking over it?

Looks good to me. To avoid having some invalid value in `n`, which is not `nil` after the first check, we could also do a 

```
    if not TLS_VERSIONS[n] then
        n = txn.f:ssl_fc_protocol_hello_id()
    end
```
as fallback, or assign TLS_VERSIONS[n] already after the initial loop and then check with `if not n` which then should always be `nil` if there no corresponding value in our table.

> I guess we could do a binary comparison, which might be cheaper than Binary => Int/String => Array Split =[LOOP]=> Int

I created a version that does the comparison without the conversions to string and back to number

```lua
local function tls_version(txn)
    local vers_bin = txn.f:ssl_fc_supported_versions_bin()
    local n

    if #vers_bin >= 2 then
        local max_vers_bin = 0

        -- Directly loop through the binary string, unpacking and comparing in one step
        for i = 1, #vers_bin, 2 do
            local current_vers_bin = string.unpack(">I2", vers_bin, i)
            if current_vers_bin > max_vers_bin then
                max_vers_bin = current_vers_bin
            end
        end

        n = TLS_VERSIONS[max_vers_bin]
    end

    if not n then
        n = TLS_VERSIONS[txn.f:ssl_fc_protocol_hello_id()]
    end

    return n or '00'
end
```

and ran a benchmark

```
Test cycles:    100000000
Original time:  64.915069       seconds
Optimized time: 31.701952       seconds
Speedup:        2.0476678849302 x
```

might be worth it.

> BTW: ssl_fc_supported_versions_bin(1) with the (1) did die on me as the GREASE is not yet in the branch (?)

Yes. This will be added next week hopefully. I called it already with `1` in my changes so that it will "just work" once the feature is added.

**Comment by mat1010** [comment]
Fyi.: the latest version in haproxies master branch has all our fetch methods + the GREASE exclude in `ssl_fc_supported_versions_bin` included.

**Pull request merged**
