### PR TITLE
fix alpn value

### PR DESCRIPTION
**Pull request by nakoo**
In rare cases, the ALPN value may be 'http/1.1'. The current implementation returns the entire ALPN value, which results in the following issue:

[14/Sep/2024:03:35:58.419] https~ https/<NOSRV> -1/-1/-1/-1/0 -1 0 - - PR-- 25/24/0/0/0 0/0 "GET /.well-known/nodeinfo HTTP/1.1" 0/0000000000000000/0/0/0 example.com/TLSv1.3/TLS_CHACHA20_POLY1305_SHA256 __"t13d3613http/1.1_018971650b2c_5f333c0549e8"__ "t_13_d_36_13_http/1.1_002f,0033,0035,0039,003c,003d,0067,006b,009c,009d,009e,009f,00ff,1301,1302,1303,1304,c009,c00a,c013,c014,c023,c027,c02b,c02c,c02f,c030,c09c,c09d,c09e,c09f,c0ac,c0ad,cca8,cca9,ccaa_000a,000b,000d,0015,0016,0017,002b,002d,0031,0033,3374_0403,05"

This PR addresses the problem by extracting only the first letter and last letter from the ALPN value, as specified in the JA4 spec.

### CODE REVIEW

**Comment by nakoo** [comment]
After conducting research, I found that the current python implementations do not align with the latest JA4 specification. Consequently, I made some adjustments to the code.

**Comment by superstes** [comment]
Sorry for the delay. Must've overlooked the notification(s)..

Thank you - I have not found a list of values that are returned by HAProxy. Thought this might be an edge-case.

Just a thought - the fc/lc handling looks a little over-engineered to me.
If it's just `http/1.1` - why not simply match the whole string instead as we already do with the `00` case?

**Comment by nakoo** [comment]
The challenge with ALPN is that it includes numerous possible combinations. For a comprehensive list, please refer to the IANA ALPN Protocol IDs [^1]. You can also check out the recent discussion regarding the ALPN value of JA4 here [^2].


[^1]: https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids
[^2]: https://github.com/FoxIO-LLC/ja4/issues/148

**Comment by superstes** [comment]
@mat1010 May you please take a look? Your opinion would be appreciated

**Comment by mat1010** [comment]
Thanks for bringing this up. I also had a look on the updated JA4 spec regarding the ALPN value cases. The updated spec has defined quite a ruleset how to handle the different potential values.

This PR handles case 1 and 2 afaict. We still have to handle Case 3, right  @nakoo ? 

## Case 1
> The first and last alphanumeric characters of the ALPN (Application-Layer Protocol Negotiation) first value.
List of possible ALPN Values (scroll down): https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml

## Case 2
> If the first or last byte of the first ALPN is non-alphanumeric (meaning not 0x30-0x39, 0x41-0x5A, or 0x61-0x7A), then we print the first and last characters of the hex representation of the first ALPN instead. For example:
>
> -   0xAB would be printed as "ab"
> -   0xAB 0xCD would be printed as "ad"
> -   0x30 0xAB would be printed as "3b"
> -   0x30 0x31 0xAB 0xCD would be printed as "3d"
> -   0x30 0xAB 0xCD 0x31 would be printed as "01"

## Case 3

> If there is no ALPN extension, no ALPN values, or the first ALPN value is empty, then we print "00" as the value in the fingerprint. If the first ALPN value is only a single character, then that character is treated as both the first and last character.

**Comment by nakoo** [comment]
> Thanks for bringing this up. I also had a look on the updated JA4 spec regarding the ALPN value cases. The updated spec has defined quite a ruleset how to handle the different potential values.
> 
> This PR handles case 1 and 2 afaict. We still have to handle Case 3, right @nakoo ?
> 

I believe Case 3 is already being addressed in the current codebase. If there is anything missing or needs improvement, please let me know.

**Review by superstes — APPROVED** [review]

**Pull request merged**
