### PR TITLE
fix ciphers hash

### PR DESCRIPTION
**Pull request by mat1010**
This change removes unnecessary string and lower conversions and fixes the table concatenation of the list of ciphers. The ciphers hash now matches the expected hash of the ja4 reference implementation.

### CODE REVIEW

**Comment by superstes** [comment]
1. The `to_string` make sense - have copied them over from my ja3n LUA-script.

2. Just to make sure: where did you find that they hash the comma-separated string?

I looked into the python3 implementation and it looks like they only sha-encode the list (without commas):
* [get_hex_sorted - return value 3 is used](https://github.com/FoxIO-LLC/ja4/blob/main/python/common.py#L114)
* [sorted_ciphers - the variable is used in the fingerprint NOT the comma-separated value](https://github.com/FoxIO-LLC/ja4/blob/main/python/ja4.py#L233)

Feel free to correct me (:

**Comment by superstes** [comment]
If that's how it should be - we may want to use the `p7_pretty` value for hashing to save on the duplicate `table.concat`

**Comment by mat1010** [comment]
> 2. Just to make sure: where did you find that they hash the comma-separated string?
>
> I looked into the python3 implementation and it looks like they only sha-encode the list (without commas):

I see what you mean. But in fact, if it is not comma separated, the hash is not correct, I verified it with the JA4 value that wireshark calculates. Let me re-check what's going on here.

Wireshark
image

Lua implementation with commas:
image


Lua implementation without commas:
image

> If that's how it should be - we may want to use the p7_pretty value for hashing to save on the duplicate table.concat

You are right, I overlooked that the `p7_pretty` var already holds the expected values. I updated the code accordingly.

**Comment by ansibleguy** [comment]
Ok, then I guess it's fine (;

**Comment by superstes** [comment]
Ok - then I guess it's fine (;

**Comment by mat1010** [comment]
@superstes I checked the docs again and they clearly state:

> Cipher hash:
> A 12 character truncated sha256 hash of the list of ciphers sorted in hex order, first 12 characters. The list is created using the 4 character hex values of the ciphers, lower case, comma delimited, ignoring GREASE.
> Example:
> ```
> 1301,1302,1303,c02b,c02f,c02c,c030,cca9,cca8,c013,c014,009c,009d,002f,0035
> ```

While checking the code again I might have found the explanation. `c` is of type list and directly provided to the `sha_encode` function which then joins the values, if it's a list, by its own and comma separates them.

```
# Joins an array by commas in the order they are presented
# and returns the first 12 chars of the sha256 hash
def sha_encode(values):
    if isinstance(values, list):
        return sha256(','.join(values).encode('utf8')).hexdigest()[:12]
    else:
        return sha256(values.encode('utf8')).hexdigest()[:12]
```

therefore it also uses the comma separated values indirectly.

**Comment by superstes** [comment]
Thank you for re-checking - makes sense.
Have not thought to look into that function 🤔

**Pull request merged**
